\info{author, Suetonius}
\info{title, The Twelve Caesars}
\info{stylesheet, suetonius.css}

\chapter{Caius Julius Caesar}
Julius Caesar, the Divine, lost his father when he was in his sixteenth year of age.

% Heavily rephrased.
One day, Sylla said to some \emph{friends}, who were entreating him to be nice to Caesar: \e{Yeah,
sure, he can hang with us.

But you do know, right, that this kid you're so worked up about his safety, he's gonna be our
downfall eventually?

I mean, you told me to take care of the nobles, but this guy's cut from the same cloth as Marius.}
