\info{author, Suetonius}
\info{title, The Twelve Caesars}
\info{stylesheet, suetonius.css}

\chapter{Caius Julius Caesar}
Julius Caesar, the Divine, lost his father when he was in his
sixteenth\footnote{Fifteen, by modern Western reckoning.} year of age.

% Heavily rephrased.
One day, Sylla said to some \emph{friends}, who were entreating him to be nice
to Caesar: \e{Yeah, sure, he can hang with us.

But you do know, right, that this kid you're so worked up about his safety, he's
gonna be our downfall eventually?

I mean, you told me to take care of the nobles, but this guy's cut from the same
cloth as Marius.\footnote{Caius Marius, the Third Founder of Rome, who
instituted significant reforms on the back of military victories and political
popularity.}}

So Julius Caesar went to the army and served as an officer under General M.
Thermus in Anatolia\footnote{The region was called \e{Asia} at the time.}. Our
boy J was sent off to the northeast, to the coast of the Black Sea, to raise a
fleet, but he stuck around Nicomedes's court so long, people started saying they
were thick as thieves, heavy on the \b{thieves}. So he ran off away from the
rumors and actually got around to raising that fleet. He did okay in the
military after that, even got a civic crown\footnote{A military medal for saving
Roman citizens or for stalwart defense.} out of the deal.

\chapter{Tiberius Nero Caesar}
